/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as HomeImport } from './routes/home';
import { Route as GameImport } from './routes/game';
import { Route as AboutImport } from './routes/about';
import { Route as LearnRouteImport } from './routes/learn/route';
import { Route as BlogRouteImport } from './routes/blog/route';
import { Route as IndexImport } from './routes/index';
import { Route as LearnIndexImport } from './routes/learn/index';
import { Route as BlogIndexImport } from './routes/blog/index';
import { Route as LearnPostsPythonIndexImport } from './routes/learn/posts/python/index';
import { Route as LearnPostsMathIndexImport } from './routes/learn/posts/math/index';
import { Route as LearnPostsGitIndexImport } from './routes/learn/posts/git/index';
import { Route as LearnPostsDsaIndexImport } from './routes/learn/posts/dsa/index';
import { Route as LearnPostsAiIndexImport } from './routes/learn/posts/ai/index';
import { Route as BlogPostsSoftSkillsIndexImport } from './routes/blog/posts/soft-skills/index';
import { Route as BlogPostsFrontendDesignIndexImport } from './routes/blog/posts/frontend-design/index';
import { Route as LearnPostsPythonWhiteboardingEssentialsImport } from './routes/learn/posts/python/whiteboarding-essentials';
import { Route as LearnPostsPythonStylingExampleImport } from './routes/learn/posts/python/styling-example';
import { Route as LearnPostsPythonDataStructuresDeepDiveImport } from './routes/learn/posts/python/data-structures-deep-dive';
import { Route as LearnPostsMathHelloWorldImport } from './routes/learn/posts/math/hello-world';
import { Route as LearnPostsGitHelloWorldImport } from './routes/learn/posts/git/hello-world';
import { Route as LearnPostsDsaHelloWorldImport } from './routes/learn/posts/dsa/hello-world';
import { Route as LearnPostsAiHelloWorldImport } from './routes/learn/posts/ai/hello-world';
import { Route as BlogPostsSoftSkillsLearnNamesImport } from './routes/blog/posts/soft-skills/learn-names';
import { Route as BlogPostsReactMemoMonsterImport } from './routes/blog/posts/react/memo-monster';
import { Route as BlogPostsFrontendDesignMicrofrontendsPart3Import } from './routes/blog/posts/frontend-design/microfrontends-part3';
import { Route as BlogPostsFrontendDesignMicrofrontendsPart2Import } from './routes/blog/posts/frontend-design/microfrontends-part2';
import { Route as BlogPostsFrontendDesignMicrofrontendsPart1Import } from './routes/blog/posts/frontend-design/microfrontends-part1';

// Create/Update Routes

const HomeRoute = HomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRoute,
} as any);

const GameRoute = GameImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRoute,
} as any);

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any);

const LearnRouteRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRoute,
} as any);

const BlogRouteRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

const LearnIndexRoute = LearnIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnRouteRoute,
} as any);

const BlogIndexRoute = BlogIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRouteRoute,
} as any);

const LearnPostsPythonIndexRoute = LearnPostsPythonIndexImport.update({
  id: '/posts/python/',
  path: '/posts/python/',
  getParentRoute: () => LearnRouteRoute,
} as any);

const LearnPostsMathIndexRoute = LearnPostsMathIndexImport.update({
  id: '/posts/math/',
  path: '/posts/math/',
  getParentRoute: () => LearnRouteRoute,
} as any);

const LearnPostsGitIndexRoute = LearnPostsGitIndexImport.update({
  id: '/posts/git/',
  path: '/posts/git/',
  getParentRoute: () => LearnRouteRoute,
} as any);

const LearnPostsDsaIndexRoute = LearnPostsDsaIndexImport.update({
  id: '/posts/dsa/',
  path: '/posts/dsa/',
  getParentRoute: () => LearnRouteRoute,
} as any);

const LearnPostsAiIndexRoute = LearnPostsAiIndexImport.update({
  id: '/posts/ai/',
  path: '/posts/ai/',
  getParentRoute: () => LearnRouteRoute,
} as any);

const BlogPostsSoftSkillsIndexRoute = BlogPostsSoftSkillsIndexImport.update({
  id: '/posts/soft-skills/',
  path: '/posts/soft-skills/',
  getParentRoute: () => BlogRouteRoute,
} as any);

const BlogPostsFrontendDesignIndexRoute =
  BlogPostsFrontendDesignIndexImport.update({
    id: '/posts/frontend-design/',
    path: '/posts/frontend-design/',
    getParentRoute: () => BlogRouteRoute,
  } as any);

const LearnPostsPythonWhiteboardingEssentialsRoute =
  LearnPostsPythonWhiteboardingEssentialsImport.update({
    id: '/posts/python/whiteboarding-essentials',
    path: '/posts/python/whiteboarding-essentials',
    getParentRoute: () => LearnRouteRoute,
  } as any);

const LearnPostsPythonStylingExampleRoute =
  LearnPostsPythonStylingExampleImport.update({
    id: '/posts/python/styling-example',
    path: '/posts/python/styling-example',
    getParentRoute: () => LearnRouteRoute,
  } as any);

const LearnPostsPythonDataStructuresDeepDiveRoute =
  LearnPostsPythonDataStructuresDeepDiveImport.update({
    id: '/posts/python/data-structures-deep-dive',
    path: '/posts/python/data-structures-deep-dive',
    getParentRoute: () => LearnRouteRoute,
  } as any);

const LearnPostsMathHelloWorldRoute = LearnPostsMathHelloWorldImport.update({
  id: '/posts/math/hello-world',
  path: '/posts/math/hello-world',
  getParentRoute: () => LearnRouteRoute,
} as any);

const LearnPostsGitHelloWorldRoute = LearnPostsGitHelloWorldImport.update({
  id: '/posts/git/hello-world',
  path: '/posts/git/hello-world',
  getParentRoute: () => LearnRouteRoute,
} as any);

const LearnPostsDsaHelloWorldRoute = LearnPostsDsaHelloWorldImport.update({
  id: '/posts/dsa/hello-world',
  path: '/posts/dsa/hello-world',
  getParentRoute: () => LearnRouteRoute,
} as any);

const LearnPostsAiHelloWorldRoute = LearnPostsAiHelloWorldImport.update({
  id: '/posts/ai/hello-world',
  path: '/posts/ai/hello-world',
  getParentRoute: () => LearnRouteRoute,
} as any);

const BlogPostsSoftSkillsLearnNamesRoute =
  BlogPostsSoftSkillsLearnNamesImport.update({
    id: '/posts/soft-skills/learn-names',
    path: '/posts/soft-skills/learn-names',
    getParentRoute: () => BlogRouteRoute,
  } as any);

const BlogPostsReactMemoMonsterRoute = BlogPostsReactMemoMonsterImport.update({
  id: '/posts/react/memo-monster',
  path: '/posts/react/memo-monster',
  getParentRoute: () => BlogRouteRoute,
} as any);

const BlogPostsFrontendDesignMicrofrontendsPart3Route =
  BlogPostsFrontendDesignMicrofrontendsPart3Import.update({
    id: '/posts/frontend-design/microfrontends-part3',
    path: '/posts/frontend-design/microfrontends-part3',
    getParentRoute: () => BlogRouteRoute,
  } as any);

const BlogPostsFrontendDesignMicrofrontendsPart2Route =
  BlogPostsFrontendDesignMicrofrontendsPart2Import.update({
    id: '/posts/frontend-design/microfrontends-part2',
    path: '/posts/frontend-design/microfrontends-part2',
    getParentRoute: () => BlogRouteRoute,
  } as any);

const BlogPostsFrontendDesignMicrofrontendsPart1Route =
  BlogPostsFrontendDesignMicrofrontendsPart1Import.update({
    id: '/posts/frontend-design/microfrontends-part1',
    path: '/posts/frontend-design/microfrontends-part1',
    getParentRoute: () => BlogRouteRoute,
  } as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/blog': {
      id: '/blog';
      path: '/blog';
      fullPath: '/blog';
      preLoaderRoute: typeof BlogRouteImport;
      parentRoute: typeof rootRoute;
    };
    '/learn': {
      id: '/learn';
      path: '/learn';
      fullPath: '/learn';
      preLoaderRoute: typeof LearnRouteImport;
      parentRoute: typeof rootRoute;
    };
    '/about': {
      id: '/about';
      path: '/about';
      fullPath: '/about';
      preLoaderRoute: typeof AboutImport;
      parentRoute: typeof rootRoute;
    };
    '/game': {
      id: '/game';
      path: '/game';
      fullPath: '/game';
      preLoaderRoute: typeof GameImport;
      parentRoute: typeof rootRoute;
    };
    '/home': {
      id: '/home';
      path: '/home';
      fullPath: '/home';
      preLoaderRoute: typeof HomeImport;
      parentRoute: typeof rootRoute;
    };
    '/blog/': {
      id: '/blog/';
      path: '/';
      fullPath: '/blog/';
      preLoaderRoute: typeof BlogIndexImport;
      parentRoute: typeof BlogRouteImport;
    };
    '/learn/': {
      id: '/learn/';
      path: '/';
      fullPath: '/learn/';
      preLoaderRoute: typeof LearnIndexImport;
      parentRoute: typeof LearnRouteImport;
    };
    '/blog/posts/frontend-design/microfrontends-part1': {
      id: '/blog/posts/frontend-design/microfrontends-part1';
      path: '/posts/frontend-design/microfrontends-part1';
      fullPath: '/blog/posts/frontend-design/microfrontends-part1';
      preLoaderRoute: typeof BlogPostsFrontendDesignMicrofrontendsPart1Import;
      parentRoute: typeof BlogRouteImport;
    };
    '/blog/posts/frontend-design/microfrontends-part2': {
      id: '/blog/posts/frontend-design/microfrontends-part2';
      path: '/posts/frontend-design/microfrontends-part2';
      fullPath: '/blog/posts/frontend-design/microfrontends-part2';
      preLoaderRoute: typeof BlogPostsFrontendDesignMicrofrontendsPart2Import;
      parentRoute: typeof BlogRouteImport;
    };
    '/blog/posts/frontend-design/microfrontends-part3': {
      id: '/blog/posts/frontend-design/microfrontends-part3';
      path: '/posts/frontend-design/microfrontends-part3';
      fullPath: '/blog/posts/frontend-design/microfrontends-part3';
      preLoaderRoute: typeof BlogPostsFrontendDesignMicrofrontendsPart3Import;
      parentRoute: typeof BlogRouteImport;
    };
    '/blog/posts/react/memo-monster': {
      id: '/blog/posts/react/memo-monster';
      path: '/posts/react/memo-monster';
      fullPath: '/blog/posts/react/memo-monster';
      preLoaderRoute: typeof BlogPostsReactMemoMonsterImport;
      parentRoute: typeof BlogRouteImport;
    };
    '/blog/posts/soft-skills/learn-names': {
      id: '/blog/posts/soft-skills/learn-names';
      path: '/posts/soft-skills/learn-names';
      fullPath: '/blog/posts/soft-skills/learn-names';
      preLoaderRoute: typeof BlogPostsSoftSkillsLearnNamesImport;
      parentRoute: typeof BlogRouteImport;
    };
    '/learn/posts/ai/hello-world': {
      id: '/learn/posts/ai/hello-world';
      path: '/posts/ai/hello-world';
      fullPath: '/learn/posts/ai/hello-world';
      preLoaderRoute: typeof LearnPostsAiHelloWorldImport;
      parentRoute: typeof LearnRouteImport;
    };
    '/learn/posts/dsa/hello-world': {
      id: '/learn/posts/dsa/hello-world';
      path: '/posts/dsa/hello-world';
      fullPath: '/learn/posts/dsa/hello-world';
      preLoaderRoute: typeof LearnPostsDsaHelloWorldImport;
      parentRoute: typeof LearnRouteImport;
    };
    '/learn/posts/git/hello-world': {
      id: '/learn/posts/git/hello-world';
      path: '/posts/git/hello-world';
      fullPath: '/learn/posts/git/hello-world';
      preLoaderRoute: typeof LearnPostsGitHelloWorldImport;
      parentRoute: typeof LearnRouteImport;
    };
    '/learn/posts/math/hello-world': {
      id: '/learn/posts/math/hello-world';
      path: '/posts/math/hello-world';
      fullPath: '/learn/posts/math/hello-world';
      preLoaderRoute: typeof LearnPostsMathHelloWorldImport;
      parentRoute: typeof LearnRouteImport;
    };
    '/learn/posts/python/data-structures-deep-dive': {
      id: '/learn/posts/python/data-structures-deep-dive';
      path: '/posts/python/data-structures-deep-dive';
      fullPath: '/learn/posts/python/data-structures-deep-dive';
      preLoaderRoute: typeof LearnPostsPythonDataStructuresDeepDiveImport;
      parentRoute: typeof LearnRouteImport;
    };
    '/learn/posts/python/styling-example': {
      id: '/learn/posts/python/styling-example';
      path: '/posts/python/styling-example';
      fullPath: '/learn/posts/python/styling-example';
      preLoaderRoute: typeof LearnPostsPythonStylingExampleImport;
      parentRoute: typeof LearnRouteImport;
    };
    '/learn/posts/python/whiteboarding-essentials': {
      id: '/learn/posts/python/whiteboarding-essentials';
      path: '/posts/python/whiteboarding-essentials';
      fullPath: '/learn/posts/python/whiteboarding-essentials';
      preLoaderRoute: typeof LearnPostsPythonWhiteboardingEssentialsImport;
      parentRoute: typeof LearnRouteImport;
    };
    '/blog/posts/frontend-design/': {
      id: '/blog/posts/frontend-design/';
      path: '/posts/frontend-design';
      fullPath: '/blog/posts/frontend-design';
      preLoaderRoute: typeof BlogPostsFrontendDesignIndexImport;
      parentRoute: typeof BlogRouteImport;
    };
    '/blog/posts/soft-skills/': {
      id: '/blog/posts/soft-skills/';
      path: '/posts/soft-skills';
      fullPath: '/blog/posts/soft-skills';
      preLoaderRoute: typeof BlogPostsSoftSkillsIndexImport;
      parentRoute: typeof BlogRouteImport;
    };
    '/learn/posts/ai/': {
      id: '/learn/posts/ai/';
      path: '/posts/ai';
      fullPath: '/learn/posts/ai';
      preLoaderRoute: typeof LearnPostsAiIndexImport;
      parentRoute: typeof LearnRouteImport;
    };
    '/learn/posts/dsa/': {
      id: '/learn/posts/dsa/';
      path: '/posts/dsa';
      fullPath: '/learn/posts/dsa';
      preLoaderRoute: typeof LearnPostsDsaIndexImport;
      parentRoute: typeof LearnRouteImport;
    };
    '/learn/posts/git/': {
      id: '/learn/posts/git/';
      path: '/posts/git';
      fullPath: '/learn/posts/git';
      preLoaderRoute: typeof LearnPostsGitIndexImport;
      parentRoute: typeof LearnRouteImport;
    };
    '/learn/posts/math/': {
      id: '/learn/posts/math/';
      path: '/posts/math';
      fullPath: '/learn/posts/math';
      preLoaderRoute: typeof LearnPostsMathIndexImport;
      parentRoute: typeof LearnRouteImport;
    };
    '/learn/posts/python/': {
      id: '/learn/posts/python/';
      path: '/posts/python';
      fullPath: '/learn/posts/python';
      preLoaderRoute: typeof LearnPostsPythonIndexImport;
      parentRoute: typeof LearnRouteImport;
    };
  }
}

// Create and export the route tree

interface BlogRouteRouteChildren {
  BlogIndexRoute: typeof BlogIndexRoute;
  BlogPostsFrontendDesignMicrofrontendsPart1Route: typeof BlogPostsFrontendDesignMicrofrontendsPart1Route;
  BlogPostsFrontendDesignMicrofrontendsPart2Route: typeof BlogPostsFrontendDesignMicrofrontendsPart2Route;
  BlogPostsFrontendDesignMicrofrontendsPart3Route: typeof BlogPostsFrontendDesignMicrofrontendsPart3Route;
  BlogPostsReactMemoMonsterRoute: typeof BlogPostsReactMemoMonsterRoute;
  BlogPostsSoftSkillsLearnNamesRoute: typeof BlogPostsSoftSkillsLearnNamesRoute;
  BlogPostsFrontendDesignIndexRoute: typeof BlogPostsFrontendDesignIndexRoute;
  BlogPostsSoftSkillsIndexRoute: typeof BlogPostsSoftSkillsIndexRoute;
}

const BlogRouteRouteChildren: BlogRouteRouteChildren = {
  BlogIndexRoute: BlogIndexRoute,
  BlogPostsFrontendDesignMicrofrontendsPart1Route:
    BlogPostsFrontendDesignMicrofrontendsPart1Route,
  BlogPostsFrontendDesignMicrofrontendsPart2Route:
    BlogPostsFrontendDesignMicrofrontendsPart2Route,
  BlogPostsFrontendDesignMicrofrontendsPart3Route:
    BlogPostsFrontendDesignMicrofrontendsPart3Route,
  BlogPostsReactMemoMonsterRoute: BlogPostsReactMemoMonsterRoute,
  BlogPostsSoftSkillsLearnNamesRoute: BlogPostsSoftSkillsLearnNamesRoute,
  BlogPostsFrontendDesignIndexRoute: BlogPostsFrontendDesignIndexRoute,
  BlogPostsSoftSkillsIndexRoute: BlogPostsSoftSkillsIndexRoute,
};

const BlogRouteRouteWithChildren = BlogRouteRoute._addFileChildren(
  BlogRouteRouteChildren
);

interface LearnRouteRouteChildren {
  LearnIndexRoute: typeof LearnIndexRoute;
  LearnPostsAiHelloWorldRoute: typeof LearnPostsAiHelloWorldRoute;
  LearnPostsDsaHelloWorldRoute: typeof LearnPostsDsaHelloWorldRoute;
  LearnPostsGitHelloWorldRoute: typeof LearnPostsGitHelloWorldRoute;
  LearnPostsMathHelloWorldRoute: typeof LearnPostsMathHelloWorldRoute;
  LearnPostsPythonDataStructuresDeepDiveRoute: typeof LearnPostsPythonDataStructuresDeepDiveRoute;
  LearnPostsPythonStylingExampleRoute: typeof LearnPostsPythonStylingExampleRoute;
  LearnPostsPythonWhiteboardingEssentialsRoute: typeof LearnPostsPythonWhiteboardingEssentialsRoute;
  LearnPostsAiIndexRoute: typeof LearnPostsAiIndexRoute;
  LearnPostsDsaIndexRoute: typeof LearnPostsDsaIndexRoute;
  LearnPostsGitIndexRoute: typeof LearnPostsGitIndexRoute;
  LearnPostsMathIndexRoute: typeof LearnPostsMathIndexRoute;
  LearnPostsPythonIndexRoute: typeof LearnPostsPythonIndexRoute;
}

const LearnRouteRouteChildren: LearnRouteRouteChildren = {
  LearnIndexRoute: LearnIndexRoute,
  LearnPostsAiHelloWorldRoute: LearnPostsAiHelloWorldRoute,
  LearnPostsDsaHelloWorldRoute: LearnPostsDsaHelloWorldRoute,
  LearnPostsGitHelloWorldRoute: LearnPostsGitHelloWorldRoute,
  LearnPostsMathHelloWorldRoute: LearnPostsMathHelloWorldRoute,
  LearnPostsPythonDataStructuresDeepDiveRoute:
    LearnPostsPythonDataStructuresDeepDiveRoute,
  LearnPostsPythonStylingExampleRoute: LearnPostsPythonStylingExampleRoute,
  LearnPostsPythonWhiteboardingEssentialsRoute:
    LearnPostsPythonWhiteboardingEssentialsRoute,
  LearnPostsAiIndexRoute: LearnPostsAiIndexRoute,
  LearnPostsDsaIndexRoute: LearnPostsDsaIndexRoute,
  LearnPostsGitIndexRoute: LearnPostsGitIndexRoute,
  LearnPostsMathIndexRoute: LearnPostsMathIndexRoute,
  LearnPostsPythonIndexRoute: LearnPostsPythonIndexRoute,
};

const LearnRouteRouteWithChildren = LearnRouteRoute._addFileChildren(
  LearnRouteRouteChildren
);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/blog': typeof BlogRouteRouteWithChildren;
  '/learn': typeof LearnRouteRouteWithChildren;
  '/about': typeof AboutRoute;
  '/game': typeof GameRoute;
  '/home': typeof HomeRoute;
  '/blog/': typeof BlogIndexRoute;
  '/learn/': typeof LearnIndexRoute;
  '/blog/posts/frontend-design/microfrontends-part1': typeof BlogPostsFrontendDesignMicrofrontendsPart1Route;
  '/blog/posts/frontend-design/microfrontends-part2': typeof BlogPostsFrontendDesignMicrofrontendsPart2Route;
  '/blog/posts/frontend-design/microfrontends-part3': typeof BlogPostsFrontendDesignMicrofrontendsPart3Route;
  '/blog/posts/react/memo-monster': typeof BlogPostsReactMemoMonsterRoute;
  '/blog/posts/soft-skills/learn-names': typeof BlogPostsSoftSkillsLearnNamesRoute;
  '/learn/posts/ai/hello-world': typeof LearnPostsAiHelloWorldRoute;
  '/learn/posts/dsa/hello-world': typeof LearnPostsDsaHelloWorldRoute;
  '/learn/posts/git/hello-world': typeof LearnPostsGitHelloWorldRoute;
  '/learn/posts/math/hello-world': typeof LearnPostsMathHelloWorldRoute;
  '/learn/posts/python/data-structures-deep-dive': typeof LearnPostsPythonDataStructuresDeepDiveRoute;
  '/learn/posts/python/styling-example': typeof LearnPostsPythonStylingExampleRoute;
  '/learn/posts/python/whiteboarding-essentials': typeof LearnPostsPythonWhiteboardingEssentialsRoute;
  '/blog/posts/frontend-design': typeof BlogPostsFrontendDesignIndexRoute;
  '/blog/posts/soft-skills': typeof BlogPostsSoftSkillsIndexRoute;
  '/learn/posts/ai': typeof LearnPostsAiIndexRoute;
  '/learn/posts/dsa': typeof LearnPostsDsaIndexRoute;
  '/learn/posts/git': typeof LearnPostsGitIndexRoute;
  '/learn/posts/math': typeof LearnPostsMathIndexRoute;
  '/learn/posts/python': typeof LearnPostsPythonIndexRoute;
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/about': typeof AboutRoute;
  '/game': typeof GameRoute;
  '/home': typeof HomeRoute;
  '/blog': typeof BlogIndexRoute;
  '/learn': typeof LearnIndexRoute;
  '/blog/posts/frontend-design/microfrontends-part1': typeof BlogPostsFrontendDesignMicrofrontendsPart1Route;
  '/blog/posts/frontend-design/microfrontends-part2': typeof BlogPostsFrontendDesignMicrofrontendsPart2Route;
  '/blog/posts/frontend-design/microfrontends-part3': typeof BlogPostsFrontendDesignMicrofrontendsPart3Route;
  '/blog/posts/react/memo-monster': typeof BlogPostsReactMemoMonsterRoute;
  '/blog/posts/soft-skills/learn-names': typeof BlogPostsSoftSkillsLearnNamesRoute;
  '/learn/posts/ai/hello-world': typeof LearnPostsAiHelloWorldRoute;
  '/learn/posts/dsa/hello-world': typeof LearnPostsDsaHelloWorldRoute;
  '/learn/posts/git/hello-world': typeof LearnPostsGitHelloWorldRoute;
  '/learn/posts/math/hello-world': typeof LearnPostsMathHelloWorldRoute;
  '/learn/posts/python/data-structures-deep-dive': typeof LearnPostsPythonDataStructuresDeepDiveRoute;
  '/learn/posts/python/styling-example': typeof LearnPostsPythonStylingExampleRoute;
  '/learn/posts/python/whiteboarding-essentials': typeof LearnPostsPythonWhiteboardingEssentialsRoute;
  '/blog/posts/frontend-design': typeof BlogPostsFrontendDesignIndexRoute;
  '/blog/posts/soft-skills': typeof BlogPostsSoftSkillsIndexRoute;
  '/learn/posts/ai': typeof LearnPostsAiIndexRoute;
  '/learn/posts/dsa': typeof LearnPostsDsaIndexRoute;
  '/learn/posts/git': typeof LearnPostsGitIndexRoute;
  '/learn/posts/math': typeof LearnPostsMathIndexRoute;
  '/learn/posts/python': typeof LearnPostsPythonIndexRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/': typeof IndexRoute;
  '/blog': typeof BlogRouteRouteWithChildren;
  '/learn': typeof LearnRouteRouteWithChildren;
  '/about': typeof AboutRoute;
  '/game': typeof GameRoute;
  '/home': typeof HomeRoute;
  '/blog/': typeof BlogIndexRoute;
  '/learn/': typeof LearnIndexRoute;
  '/blog/posts/frontend-design/microfrontends-part1': typeof BlogPostsFrontendDesignMicrofrontendsPart1Route;
  '/blog/posts/frontend-design/microfrontends-part2': typeof BlogPostsFrontendDesignMicrofrontendsPart2Route;
  '/blog/posts/frontend-design/microfrontends-part3': typeof BlogPostsFrontendDesignMicrofrontendsPart3Route;
  '/blog/posts/react/memo-monster': typeof BlogPostsReactMemoMonsterRoute;
  '/blog/posts/soft-skills/learn-names': typeof BlogPostsSoftSkillsLearnNamesRoute;
  '/learn/posts/ai/hello-world': typeof LearnPostsAiHelloWorldRoute;
  '/learn/posts/dsa/hello-world': typeof LearnPostsDsaHelloWorldRoute;
  '/learn/posts/git/hello-world': typeof LearnPostsGitHelloWorldRoute;
  '/learn/posts/math/hello-world': typeof LearnPostsMathHelloWorldRoute;
  '/learn/posts/python/data-structures-deep-dive': typeof LearnPostsPythonDataStructuresDeepDiveRoute;
  '/learn/posts/python/styling-example': typeof LearnPostsPythonStylingExampleRoute;
  '/learn/posts/python/whiteboarding-essentials': typeof LearnPostsPythonWhiteboardingEssentialsRoute;
  '/blog/posts/frontend-design/': typeof BlogPostsFrontendDesignIndexRoute;
  '/blog/posts/soft-skills/': typeof BlogPostsSoftSkillsIndexRoute;
  '/learn/posts/ai/': typeof LearnPostsAiIndexRoute;
  '/learn/posts/dsa/': typeof LearnPostsDsaIndexRoute;
  '/learn/posts/git/': typeof LearnPostsGitIndexRoute;
  '/learn/posts/math/': typeof LearnPostsMathIndexRoute;
  '/learn/posts/python/': typeof LearnPostsPythonIndexRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/blog'
    | '/learn'
    | '/about'
    | '/game'
    | '/home'
    | '/blog/'
    | '/learn/'
    | '/blog/posts/frontend-design/microfrontends-part1'
    | '/blog/posts/frontend-design/microfrontends-part2'
    | '/blog/posts/frontend-design/microfrontends-part3'
    | '/blog/posts/react/memo-monster'
    | '/blog/posts/soft-skills/learn-names'
    | '/learn/posts/ai/hello-world'
    | '/learn/posts/dsa/hello-world'
    | '/learn/posts/git/hello-world'
    | '/learn/posts/math/hello-world'
    | '/learn/posts/python/data-structures-deep-dive'
    | '/learn/posts/python/styling-example'
    | '/learn/posts/python/whiteboarding-essentials'
    | '/blog/posts/frontend-design'
    | '/blog/posts/soft-skills'
    | '/learn/posts/ai'
    | '/learn/posts/dsa'
    | '/learn/posts/git'
    | '/learn/posts/math'
    | '/learn/posts/python';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/about'
    | '/game'
    | '/home'
    | '/blog'
    | '/learn'
    | '/blog/posts/frontend-design/microfrontends-part1'
    | '/blog/posts/frontend-design/microfrontends-part2'
    | '/blog/posts/frontend-design/microfrontends-part3'
    | '/blog/posts/react/memo-monster'
    | '/blog/posts/soft-skills/learn-names'
    | '/learn/posts/ai/hello-world'
    | '/learn/posts/dsa/hello-world'
    | '/learn/posts/git/hello-world'
    | '/learn/posts/math/hello-world'
    | '/learn/posts/python/data-structures-deep-dive'
    | '/learn/posts/python/styling-example'
    | '/learn/posts/python/whiteboarding-essentials'
    | '/blog/posts/frontend-design'
    | '/blog/posts/soft-skills'
    | '/learn/posts/ai'
    | '/learn/posts/dsa'
    | '/learn/posts/git'
    | '/learn/posts/math'
    | '/learn/posts/python';
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/learn'
    | '/about'
    | '/game'
    | '/home'
    | '/blog/'
    | '/learn/'
    | '/blog/posts/frontend-design/microfrontends-part1'
    | '/blog/posts/frontend-design/microfrontends-part2'
    | '/blog/posts/frontend-design/microfrontends-part3'
    | '/blog/posts/react/memo-monster'
    | '/blog/posts/soft-skills/learn-names'
    | '/learn/posts/ai/hello-world'
    | '/learn/posts/dsa/hello-world'
    | '/learn/posts/git/hello-world'
    | '/learn/posts/math/hello-world'
    | '/learn/posts/python/data-structures-deep-dive'
    | '/learn/posts/python/styling-example'
    | '/learn/posts/python/whiteboarding-essentials'
    | '/blog/posts/frontend-design/'
    | '/blog/posts/soft-skills/'
    | '/learn/posts/ai/'
    | '/learn/posts/dsa/'
    | '/learn/posts/git/'
    | '/learn/posts/math/'
    | '/learn/posts/python/';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  BlogRouteRoute: typeof BlogRouteRouteWithChildren;
  LearnRouteRoute: typeof LearnRouteRouteWithChildren;
  AboutRoute: typeof AboutRoute;
  GameRoute: typeof GameRoute;
  HomeRoute: typeof HomeRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRouteRoute: BlogRouteRouteWithChildren,
  LearnRouteRoute: LearnRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  GameRoute: GameRoute,
  HomeRoute: HomeRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/blog",
        "/learn",
        "/about",
        "/game",
        "/home"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/blog": {
      "filePath": "blog/route.tsx",
      "children": [
        "/blog/",
        "/blog/posts/frontend-design/microfrontends-part1",
        "/blog/posts/frontend-design/microfrontends-part2",
        "/blog/posts/frontend-design/microfrontends-part3",
        "/blog/posts/react/memo-monster",
        "/blog/posts/soft-skills/learn-names",
        "/blog/posts/frontend-design/",
        "/blog/posts/soft-skills/"
      ]
    },
    "/learn": {
      "filePath": "learn/route.tsx",
      "children": [
        "/learn/",
        "/learn/posts/ai/hello-world",
        "/learn/posts/dsa/hello-world",
        "/learn/posts/git/hello-world",
        "/learn/posts/math/hello-world",
        "/learn/posts/python/data-structures-deep-dive",
        "/learn/posts/python/styling-example",
        "/learn/posts/python/whiteboarding-essentials",
        "/learn/posts/ai/",
        "/learn/posts/dsa/",
        "/learn/posts/git/",
        "/learn/posts/math/",
        "/learn/posts/python/"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/game": {
      "filePath": "game.tsx"
    },
    "/home": {
      "filePath": "home.tsx"
    },
    "/blog/": {
      "filePath": "blog/index.tsx",
      "parent": "/blog"
    },
    "/learn/": {
      "filePath": "learn/index.tsx",
      "parent": "/learn"
    },
    "/blog/posts/frontend-design/microfrontends-part1": {
      "filePath": "blog/posts/frontend-design/microfrontends-part1.tsx",
      "parent": "/blog"
    },
    "/blog/posts/frontend-design/microfrontends-part2": {
      "filePath": "blog/posts/frontend-design/microfrontends-part2.tsx",
      "parent": "/blog"
    },
    "/blog/posts/frontend-design/microfrontends-part3": {
      "filePath": "blog/posts/frontend-design/microfrontends-part3.tsx",
      "parent": "/blog"
    },
    "/blog/posts/react/memo-monster": {
      "filePath": "blog/posts/react/memo-monster.tsx",
      "parent": "/blog"
    },
    "/blog/posts/soft-skills/learn-names": {
      "filePath": "blog/posts/soft-skills/learn-names.jsx",
      "parent": "/blog"
    },
    "/learn/posts/ai/hello-world": {
      "filePath": "learn/posts/ai/hello-world.tsx",
      "parent": "/learn"
    },
    "/learn/posts/dsa/hello-world": {
      "filePath": "learn/posts/dsa/hello-world.tsx",
      "parent": "/learn"
    },
    "/learn/posts/git/hello-world": {
      "filePath": "learn/posts/git/hello-world.tsx",
      "parent": "/learn"
    },
    "/learn/posts/math/hello-world": {
      "filePath": "learn/posts/math/hello-world.tsx",
      "parent": "/learn"
    },
    "/learn/posts/python/data-structures-deep-dive": {
      "filePath": "learn/posts/python/data-structures-deep-dive.tsx",
      "parent": "/learn"
    },
    "/learn/posts/python/styling-example": {
      "filePath": "learn/posts/python/styling-example.tsx",
      "parent": "/learn"
    },
    "/learn/posts/python/whiteboarding-essentials": {
      "filePath": "learn/posts/python/whiteboarding-essentials.tsx",
      "parent": "/learn"
    },
    "/blog/posts/frontend-design/": {
      "filePath": "blog/posts/frontend-design/index.tsx",
      "parent": "/blog"
    },
    "/blog/posts/soft-skills/": {
      "filePath": "blog/posts/soft-skills/index.tsx",
      "parent": "/blog"
    },
    "/learn/posts/ai/": {
      "filePath": "learn/posts/ai/index.tsx",
      "parent": "/learn"
    },
    "/learn/posts/dsa/": {
      "filePath": "learn/posts/dsa/index.tsx",
      "parent": "/learn"
    },
    "/learn/posts/git/": {
      "filePath": "learn/posts/git/index.tsx",
      "parent": "/learn"
    },
    "/learn/posts/math/": {
      "filePath": "learn/posts/math/index.tsx",
      "parent": "/learn"
    },
    "/learn/posts/python/": {
      "filePath": "learn/posts/python/index.tsx",
      "parent": "/learn"
    }
  }
}
ROUTE_MANIFEST_END */
