/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as HomeImport } from './routes/home'
import { Route as GameImport } from './routes/game'
import { Route as AboutImport } from './routes/about'
import { Route as LearnRouteImport } from './routes/learn/route'
import { Route as BlogRouteImport } from './routes/blog/route'
import { Route as IndexImport } from './routes/index'
import { Route as LearnIndexImport } from './routes/learn/index'
import { Route as BlogIndexImport } from './routes/blog/index'
import { Route as LearnPythonIndexImport } from './routes/learn/python/index'
import { Route as LearnMathIndexImport } from './routes/learn/math/index'
import { Route as LearnGitIndexImport } from './routes/learn/git/index'
import { Route as LearnDsaIndexImport } from './routes/learn/dsa/index'
import { Route as LearnAiIndexImport } from './routes/learn/ai/index'
import { Route as BlogSoftSkillsIndexImport } from './routes/blog/soft-skills/index'
import { Route as BlogReactIndexImport } from './routes/blog/react/index'
import { Route as BlogFrontendDesignIndexImport } from './routes/blog/frontend-design/index'
import { Route as LearnPythonWhiteboardingEssentialsImport } from './routes/learn/python/whiteboarding-essentials'
import { Route as LearnGitHelloWorldImport } from './routes/learn/git/hello-world'
import { Route as LearnDsaHelloWorldImport } from './routes/learn/dsa/hello-world'
import { Route as LearnAiHelloWorldImport } from './routes/learn/ai/hello-world'
import { Route as BlogSoftSkillsLearnNamesImport } from './routes/blog/soft-skills/learn-names'
import { Route as BlogReactMemoMonsterImport } from './routes/blog/react/memo-monster'
import { Route as BlogFrontendDesignMicrofrontendsPart3Import } from './routes/blog/frontend-design/microfrontends-part3'
import { Route as BlogFrontendDesignMicrofrontendsPart2Import } from './routes/blog/frontend-design/microfrontends-part2'
import { Route as BlogFrontendDesignMicrofrontendsPart1Import } from './routes/blog/frontend-design/microfrontends-part1'
import { Route as LearnMathHelloWorldRouteImport } from './routes/learn/math/hello-world/route'
import { Route as LearnMathHelloWorldIndexImport } from './routes/learn/math/hello-world/index'

// Create Virtual Routes

const LearnMathHelloWorldExamplesLazyImport = createFileRoute(
  '/learn/math/hello-world/examples',
)()
const LearnMathHelloWorldAdvancedLazyImport = createFileRoute(
  '/learn/math/hello-world/advanced',
)()

// Create/Update Routes

const HomeRoute = HomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRoute,
} as any)

const GameRoute = GameImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const LearnRouteRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRoute,
} as any)

const BlogRouteRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LearnIndexRoute = LearnIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnRouteRoute,
} as any)

const BlogIndexRoute = BlogIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRouteRoute,
} as any)

const LearnPythonIndexRoute = LearnPythonIndexImport.update({
  id: '/python/',
  path: '/python/',
  getParentRoute: () => LearnRouteRoute,
} as any)

const LearnMathIndexRoute = LearnMathIndexImport.update({
  id: '/math/',
  path: '/math/',
  getParentRoute: () => LearnRouteRoute,
} as any)

const LearnGitIndexRoute = LearnGitIndexImport.update({
  id: '/git/',
  path: '/git/',
  getParentRoute: () => LearnRouteRoute,
} as any)

const LearnDsaIndexRoute = LearnDsaIndexImport.update({
  id: '/dsa/',
  path: '/dsa/',
  getParentRoute: () => LearnRouteRoute,
} as any)

const LearnAiIndexRoute = LearnAiIndexImport.update({
  id: '/ai/',
  path: '/ai/',
  getParentRoute: () => LearnRouteRoute,
} as any)

const BlogSoftSkillsIndexRoute = BlogSoftSkillsIndexImport.update({
  id: '/soft-skills/',
  path: '/soft-skills/',
  getParentRoute: () => BlogRouteRoute,
} as any)

const BlogReactIndexRoute = BlogReactIndexImport.update({
  id: '/react/',
  path: '/react/',
  getParentRoute: () => BlogRouteRoute,
} as any)

const BlogFrontendDesignIndexRoute = BlogFrontendDesignIndexImport.update({
  id: '/frontend-design/',
  path: '/frontend-design/',
  getParentRoute: () => BlogRouteRoute,
} as any)

const LearnPythonWhiteboardingEssentialsRoute =
  LearnPythonWhiteboardingEssentialsImport.update({
    id: '/python/whiteboarding-essentials',
    path: '/python/whiteboarding-essentials',
    getParentRoute: () => LearnRouteRoute,
  } as any)

const LearnGitHelloWorldRoute = LearnGitHelloWorldImport.update({
  id: '/git/hello-world',
  path: '/git/hello-world',
  getParentRoute: () => LearnRouteRoute,
} as any)

const LearnDsaHelloWorldRoute = LearnDsaHelloWorldImport.update({
  id: '/dsa/hello-world',
  path: '/dsa/hello-world',
  getParentRoute: () => LearnRouteRoute,
} as any)

const LearnAiHelloWorldRoute = LearnAiHelloWorldImport.update({
  id: '/ai/hello-world',
  path: '/ai/hello-world',
  getParentRoute: () => LearnRouteRoute,
} as any)

const BlogSoftSkillsLearnNamesRoute = BlogSoftSkillsLearnNamesImport.update({
  id: '/soft-skills/learn-names',
  path: '/soft-skills/learn-names',
  getParentRoute: () => BlogRouteRoute,
} as any)

const BlogReactMemoMonsterRoute = BlogReactMemoMonsterImport.update({
  id: '/react/memo-monster',
  path: '/react/memo-monster',
  getParentRoute: () => BlogRouteRoute,
} as any)

const BlogFrontendDesignMicrofrontendsPart3Route =
  BlogFrontendDesignMicrofrontendsPart3Import.update({
    id: '/frontend-design/microfrontends-part3',
    path: '/frontend-design/microfrontends-part3',
    getParentRoute: () => BlogRouteRoute,
  } as any)

const BlogFrontendDesignMicrofrontendsPart2Route =
  BlogFrontendDesignMicrofrontendsPart2Import.update({
    id: '/frontend-design/microfrontends-part2',
    path: '/frontend-design/microfrontends-part2',
    getParentRoute: () => BlogRouteRoute,
  } as any)

const BlogFrontendDesignMicrofrontendsPart1Route =
  BlogFrontendDesignMicrofrontendsPart1Import.update({
    id: '/frontend-design/microfrontends-part1',
    path: '/frontend-design/microfrontends-part1',
    getParentRoute: () => BlogRouteRoute,
  } as any)

const LearnMathHelloWorldRouteRoute = LearnMathHelloWorldRouteImport.update({
  id: '/math/hello-world',
  path: '/math/hello-world',
  getParentRoute: () => LearnRouteRoute,
} as any)

const LearnMathHelloWorldIndexRoute = LearnMathHelloWorldIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnMathHelloWorldRouteRoute,
} as any)

const LearnMathHelloWorldExamplesLazyRoute =
  LearnMathHelloWorldExamplesLazyImport.update({
    id: '/examples',
    path: '/examples',
    getParentRoute: () => LearnMathHelloWorldRouteRoute,
  } as any).lazy(() =>
    import('./routes/learn/math/hello-world/examples.lazy').then(
      (d) => d.Route,
    ),
  )

const LearnMathHelloWorldAdvancedLazyRoute =
  LearnMathHelloWorldAdvancedLazyImport.update({
    id: '/advanced',
    path: '/advanced',
    getParentRoute: () => LearnMathHelloWorldRouteRoute,
  } as any).lazy(() =>
    import('./routes/learn/math/hello-world/advanced.lazy').then(
      (d) => d.Route,
    ),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRoute
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameImport
      parentRoute: typeof rootRoute
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeImport
      parentRoute: typeof rootRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexImport
      parentRoute: typeof BlogRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexImport
      parentRoute: typeof LearnRouteImport
    }
    '/learn/math/hello-world': {
      id: '/learn/math/hello-world'
      path: '/math/hello-world'
      fullPath: '/learn/math/hello-world'
      preLoaderRoute: typeof LearnMathHelloWorldRouteImport
      parentRoute: typeof LearnRouteImport
    }
    '/blog/frontend-design/microfrontends-part1': {
      id: '/blog/frontend-design/microfrontends-part1'
      path: '/frontend-design/microfrontends-part1'
      fullPath: '/blog/frontend-design/microfrontends-part1'
      preLoaderRoute: typeof BlogFrontendDesignMicrofrontendsPart1Import
      parentRoute: typeof BlogRouteImport
    }
    '/blog/frontend-design/microfrontends-part2': {
      id: '/blog/frontend-design/microfrontends-part2'
      path: '/frontend-design/microfrontends-part2'
      fullPath: '/blog/frontend-design/microfrontends-part2'
      preLoaderRoute: typeof BlogFrontendDesignMicrofrontendsPart2Import
      parentRoute: typeof BlogRouteImport
    }
    '/blog/frontend-design/microfrontends-part3': {
      id: '/blog/frontend-design/microfrontends-part3'
      path: '/frontend-design/microfrontends-part3'
      fullPath: '/blog/frontend-design/microfrontends-part3'
      preLoaderRoute: typeof BlogFrontendDesignMicrofrontendsPart3Import
      parentRoute: typeof BlogRouteImport
    }
    '/blog/react/memo-monster': {
      id: '/blog/react/memo-monster'
      path: '/react/memo-monster'
      fullPath: '/blog/react/memo-monster'
      preLoaderRoute: typeof BlogReactMemoMonsterImport
      parentRoute: typeof BlogRouteImport
    }
    '/blog/soft-skills/learn-names': {
      id: '/blog/soft-skills/learn-names'
      path: '/soft-skills/learn-names'
      fullPath: '/blog/soft-skills/learn-names'
      preLoaderRoute: typeof BlogSoftSkillsLearnNamesImport
      parentRoute: typeof BlogRouteImport
    }
    '/learn/ai/hello-world': {
      id: '/learn/ai/hello-world'
      path: '/ai/hello-world'
      fullPath: '/learn/ai/hello-world'
      preLoaderRoute: typeof LearnAiHelloWorldImport
      parentRoute: typeof LearnRouteImport
    }
    '/learn/dsa/hello-world': {
      id: '/learn/dsa/hello-world'
      path: '/dsa/hello-world'
      fullPath: '/learn/dsa/hello-world'
      preLoaderRoute: typeof LearnDsaHelloWorldImport
      parentRoute: typeof LearnRouteImport
    }
    '/learn/git/hello-world': {
      id: '/learn/git/hello-world'
      path: '/git/hello-world'
      fullPath: '/learn/git/hello-world'
      preLoaderRoute: typeof LearnGitHelloWorldImport
      parentRoute: typeof LearnRouteImport
    }
    '/learn/python/whiteboarding-essentials': {
      id: '/learn/python/whiteboarding-essentials'
      path: '/python/whiteboarding-essentials'
      fullPath: '/learn/python/whiteboarding-essentials'
      preLoaderRoute: typeof LearnPythonWhiteboardingEssentialsImport
      parentRoute: typeof LearnRouteImport
    }
    '/blog/frontend-design/': {
      id: '/blog/frontend-design/'
      path: '/frontend-design'
      fullPath: '/blog/frontend-design'
      preLoaderRoute: typeof BlogFrontendDesignIndexImport
      parentRoute: typeof BlogRouteImport
    }
    '/blog/react/': {
      id: '/blog/react/'
      path: '/react'
      fullPath: '/blog/react'
      preLoaderRoute: typeof BlogReactIndexImport
      parentRoute: typeof BlogRouteImport
    }
    '/blog/soft-skills/': {
      id: '/blog/soft-skills/'
      path: '/soft-skills'
      fullPath: '/blog/soft-skills'
      preLoaderRoute: typeof BlogSoftSkillsIndexImport
      parentRoute: typeof BlogRouteImport
    }
    '/learn/ai/': {
      id: '/learn/ai/'
      path: '/ai'
      fullPath: '/learn/ai'
      preLoaderRoute: typeof LearnAiIndexImport
      parentRoute: typeof LearnRouteImport
    }
    '/learn/dsa/': {
      id: '/learn/dsa/'
      path: '/dsa'
      fullPath: '/learn/dsa'
      preLoaderRoute: typeof LearnDsaIndexImport
      parentRoute: typeof LearnRouteImport
    }
    '/learn/git/': {
      id: '/learn/git/'
      path: '/git'
      fullPath: '/learn/git'
      preLoaderRoute: typeof LearnGitIndexImport
      parentRoute: typeof LearnRouteImport
    }
    '/learn/math/': {
      id: '/learn/math/'
      path: '/math'
      fullPath: '/learn/math'
      preLoaderRoute: typeof LearnMathIndexImport
      parentRoute: typeof LearnRouteImport
    }
    '/learn/python/': {
      id: '/learn/python/'
      path: '/python'
      fullPath: '/learn/python'
      preLoaderRoute: typeof LearnPythonIndexImport
      parentRoute: typeof LearnRouteImport
    }
    '/learn/math/hello-world/advanced': {
      id: '/learn/math/hello-world/advanced'
      path: '/advanced'
      fullPath: '/learn/math/hello-world/advanced'
      preLoaderRoute: typeof LearnMathHelloWorldAdvancedLazyImport
      parentRoute: typeof LearnMathHelloWorldRouteImport
    }
    '/learn/math/hello-world/examples': {
      id: '/learn/math/hello-world/examples'
      path: '/examples'
      fullPath: '/learn/math/hello-world/examples'
      preLoaderRoute: typeof LearnMathHelloWorldExamplesLazyImport
      parentRoute: typeof LearnMathHelloWorldRouteImport
    }
    '/learn/math/hello-world/': {
      id: '/learn/math/hello-world/'
      path: '/'
      fullPath: '/learn/math/hello-world/'
      preLoaderRoute: typeof LearnMathHelloWorldIndexImport
      parentRoute: typeof LearnMathHelloWorldRouteImport
    }
  }
}

// Create and export the route tree

interface BlogRouteRouteChildren {
  BlogIndexRoute: typeof BlogIndexRoute
  BlogFrontendDesignMicrofrontendsPart1Route: typeof BlogFrontendDesignMicrofrontendsPart1Route
  BlogFrontendDesignMicrofrontendsPart2Route: typeof BlogFrontendDesignMicrofrontendsPart2Route
  BlogFrontendDesignMicrofrontendsPart3Route: typeof BlogFrontendDesignMicrofrontendsPart3Route
  BlogReactMemoMonsterRoute: typeof BlogReactMemoMonsterRoute
  BlogSoftSkillsLearnNamesRoute: typeof BlogSoftSkillsLearnNamesRoute
  BlogFrontendDesignIndexRoute: typeof BlogFrontendDesignIndexRoute
  BlogReactIndexRoute: typeof BlogReactIndexRoute
  BlogSoftSkillsIndexRoute: typeof BlogSoftSkillsIndexRoute
}

const BlogRouteRouteChildren: BlogRouteRouteChildren = {
  BlogIndexRoute: BlogIndexRoute,
  BlogFrontendDesignMicrofrontendsPart1Route:
    BlogFrontendDesignMicrofrontendsPart1Route,
  BlogFrontendDesignMicrofrontendsPart2Route:
    BlogFrontendDesignMicrofrontendsPart2Route,
  BlogFrontendDesignMicrofrontendsPart3Route:
    BlogFrontendDesignMicrofrontendsPart3Route,
  BlogReactMemoMonsterRoute: BlogReactMemoMonsterRoute,
  BlogSoftSkillsLearnNamesRoute: BlogSoftSkillsLearnNamesRoute,
  BlogFrontendDesignIndexRoute: BlogFrontendDesignIndexRoute,
  BlogReactIndexRoute: BlogReactIndexRoute,
  BlogSoftSkillsIndexRoute: BlogSoftSkillsIndexRoute,
}

const BlogRouteRouteWithChildren = BlogRouteRoute._addFileChildren(
  BlogRouteRouteChildren,
)

interface LearnMathHelloWorldRouteRouteChildren {
  LearnMathHelloWorldAdvancedLazyRoute: typeof LearnMathHelloWorldAdvancedLazyRoute
  LearnMathHelloWorldExamplesLazyRoute: typeof LearnMathHelloWorldExamplesLazyRoute
  LearnMathHelloWorldIndexRoute: typeof LearnMathHelloWorldIndexRoute
}

const LearnMathHelloWorldRouteRouteChildren: LearnMathHelloWorldRouteRouteChildren =
  {
    LearnMathHelloWorldAdvancedLazyRoute: LearnMathHelloWorldAdvancedLazyRoute,
    LearnMathHelloWorldExamplesLazyRoute: LearnMathHelloWorldExamplesLazyRoute,
    LearnMathHelloWorldIndexRoute: LearnMathHelloWorldIndexRoute,
  }

const LearnMathHelloWorldRouteRouteWithChildren =
  LearnMathHelloWorldRouteRoute._addFileChildren(
    LearnMathHelloWorldRouteRouteChildren,
  )

interface LearnRouteRouteChildren {
  LearnIndexRoute: typeof LearnIndexRoute
  LearnMathHelloWorldRouteRoute: typeof LearnMathHelloWorldRouteRouteWithChildren
  LearnAiHelloWorldRoute: typeof LearnAiHelloWorldRoute
  LearnDsaHelloWorldRoute: typeof LearnDsaHelloWorldRoute
  LearnGitHelloWorldRoute: typeof LearnGitHelloWorldRoute
  LearnPythonWhiteboardingEssentialsRoute: typeof LearnPythonWhiteboardingEssentialsRoute
  LearnAiIndexRoute: typeof LearnAiIndexRoute
  LearnDsaIndexRoute: typeof LearnDsaIndexRoute
  LearnGitIndexRoute: typeof LearnGitIndexRoute
  LearnMathIndexRoute: typeof LearnMathIndexRoute
  LearnPythonIndexRoute: typeof LearnPythonIndexRoute
}

const LearnRouteRouteChildren: LearnRouteRouteChildren = {
  LearnIndexRoute: LearnIndexRoute,
  LearnMathHelloWorldRouteRoute: LearnMathHelloWorldRouteRouteWithChildren,
  LearnAiHelloWorldRoute: LearnAiHelloWorldRoute,
  LearnDsaHelloWorldRoute: LearnDsaHelloWorldRoute,
  LearnGitHelloWorldRoute: LearnGitHelloWorldRoute,
  LearnPythonWhiteboardingEssentialsRoute:
    LearnPythonWhiteboardingEssentialsRoute,
  LearnAiIndexRoute: LearnAiIndexRoute,
  LearnDsaIndexRoute: LearnDsaIndexRoute,
  LearnGitIndexRoute: LearnGitIndexRoute,
  LearnMathIndexRoute: LearnMathIndexRoute,
  LearnPythonIndexRoute: LearnPythonIndexRoute,
}

const LearnRouteRouteWithChildren = LearnRouteRoute._addFileChildren(
  LearnRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteRouteWithChildren
  '/learn': typeof LearnRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/game': typeof GameRoute
  '/home': typeof HomeRoute
  '/blog/': typeof BlogIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/learn/math/hello-world': typeof LearnMathHelloWorldRouteRouteWithChildren
  '/blog/frontend-design/microfrontends-part1': typeof BlogFrontendDesignMicrofrontendsPart1Route
  '/blog/frontend-design/microfrontends-part2': typeof BlogFrontendDesignMicrofrontendsPart2Route
  '/blog/frontend-design/microfrontends-part3': typeof BlogFrontendDesignMicrofrontendsPart3Route
  '/blog/react/memo-monster': typeof BlogReactMemoMonsterRoute
  '/blog/soft-skills/learn-names': typeof BlogSoftSkillsLearnNamesRoute
  '/learn/ai/hello-world': typeof LearnAiHelloWorldRoute
  '/learn/dsa/hello-world': typeof LearnDsaHelloWorldRoute
  '/learn/git/hello-world': typeof LearnGitHelloWorldRoute
  '/learn/python/whiteboarding-essentials': typeof LearnPythonWhiteboardingEssentialsRoute
  '/blog/frontend-design': typeof BlogFrontendDesignIndexRoute
  '/blog/react': typeof BlogReactIndexRoute
  '/blog/soft-skills': typeof BlogSoftSkillsIndexRoute
  '/learn/ai': typeof LearnAiIndexRoute
  '/learn/dsa': typeof LearnDsaIndexRoute
  '/learn/git': typeof LearnGitIndexRoute
  '/learn/math': typeof LearnMathIndexRoute
  '/learn/python': typeof LearnPythonIndexRoute
  '/learn/math/hello-world/advanced': typeof LearnMathHelloWorldAdvancedLazyRoute
  '/learn/math/hello-world/examples': typeof LearnMathHelloWorldExamplesLazyRoute
  '/learn/math/hello-world/': typeof LearnMathHelloWorldIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/game': typeof GameRoute
  '/home': typeof HomeRoute
  '/blog': typeof BlogIndexRoute
  '/learn': typeof LearnIndexRoute
  '/blog/frontend-design/microfrontends-part1': typeof BlogFrontendDesignMicrofrontendsPart1Route
  '/blog/frontend-design/microfrontends-part2': typeof BlogFrontendDesignMicrofrontendsPart2Route
  '/blog/frontend-design/microfrontends-part3': typeof BlogFrontendDesignMicrofrontendsPart3Route
  '/blog/react/memo-monster': typeof BlogReactMemoMonsterRoute
  '/blog/soft-skills/learn-names': typeof BlogSoftSkillsLearnNamesRoute
  '/learn/ai/hello-world': typeof LearnAiHelloWorldRoute
  '/learn/dsa/hello-world': typeof LearnDsaHelloWorldRoute
  '/learn/git/hello-world': typeof LearnGitHelloWorldRoute
  '/learn/python/whiteboarding-essentials': typeof LearnPythonWhiteboardingEssentialsRoute
  '/blog/frontend-design': typeof BlogFrontendDesignIndexRoute
  '/blog/react': typeof BlogReactIndexRoute
  '/blog/soft-skills': typeof BlogSoftSkillsIndexRoute
  '/learn/ai': typeof LearnAiIndexRoute
  '/learn/dsa': typeof LearnDsaIndexRoute
  '/learn/git': typeof LearnGitIndexRoute
  '/learn/math': typeof LearnMathIndexRoute
  '/learn/python': typeof LearnPythonIndexRoute
  '/learn/math/hello-world/advanced': typeof LearnMathHelloWorldAdvancedLazyRoute
  '/learn/math/hello-world/examples': typeof LearnMathHelloWorldExamplesLazyRoute
  '/learn/math/hello-world': typeof LearnMathHelloWorldIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteRouteWithChildren
  '/learn': typeof LearnRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/game': typeof GameRoute
  '/home': typeof HomeRoute
  '/blog/': typeof BlogIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/learn/math/hello-world': typeof LearnMathHelloWorldRouteRouteWithChildren
  '/blog/frontend-design/microfrontends-part1': typeof BlogFrontendDesignMicrofrontendsPart1Route
  '/blog/frontend-design/microfrontends-part2': typeof BlogFrontendDesignMicrofrontendsPart2Route
  '/blog/frontend-design/microfrontends-part3': typeof BlogFrontendDesignMicrofrontendsPart3Route
  '/blog/react/memo-monster': typeof BlogReactMemoMonsterRoute
  '/blog/soft-skills/learn-names': typeof BlogSoftSkillsLearnNamesRoute
  '/learn/ai/hello-world': typeof LearnAiHelloWorldRoute
  '/learn/dsa/hello-world': typeof LearnDsaHelloWorldRoute
  '/learn/git/hello-world': typeof LearnGitHelloWorldRoute
  '/learn/python/whiteboarding-essentials': typeof LearnPythonWhiteboardingEssentialsRoute
  '/blog/frontend-design/': typeof BlogFrontendDesignIndexRoute
  '/blog/react/': typeof BlogReactIndexRoute
  '/blog/soft-skills/': typeof BlogSoftSkillsIndexRoute
  '/learn/ai/': typeof LearnAiIndexRoute
  '/learn/dsa/': typeof LearnDsaIndexRoute
  '/learn/git/': typeof LearnGitIndexRoute
  '/learn/math/': typeof LearnMathIndexRoute
  '/learn/python/': typeof LearnPythonIndexRoute
  '/learn/math/hello-world/advanced': typeof LearnMathHelloWorldAdvancedLazyRoute
  '/learn/math/hello-world/examples': typeof LearnMathHelloWorldExamplesLazyRoute
  '/learn/math/hello-world/': typeof LearnMathHelloWorldIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/learn'
    | '/about'
    | '/game'
    | '/home'
    | '/blog/'
    | '/learn/'
    | '/learn/math/hello-world'
    | '/blog/frontend-design/microfrontends-part1'
    | '/blog/frontend-design/microfrontends-part2'
    | '/blog/frontend-design/microfrontends-part3'
    | '/blog/react/memo-monster'
    | '/blog/soft-skills/learn-names'
    | '/learn/ai/hello-world'
    | '/learn/dsa/hello-world'
    | '/learn/git/hello-world'
    | '/learn/python/whiteboarding-essentials'
    | '/blog/frontend-design'
    | '/blog/react'
    | '/blog/soft-skills'
    | '/learn/ai'
    | '/learn/dsa'
    | '/learn/git'
    | '/learn/math'
    | '/learn/python'
    | '/learn/math/hello-world/advanced'
    | '/learn/math/hello-world/examples'
    | '/learn/math/hello-world/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/game'
    | '/home'
    | '/blog'
    | '/learn'
    | '/blog/frontend-design/microfrontends-part1'
    | '/blog/frontend-design/microfrontends-part2'
    | '/blog/frontend-design/microfrontends-part3'
    | '/blog/react/memo-monster'
    | '/blog/soft-skills/learn-names'
    | '/learn/ai/hello-world'
    | '/learn/dsa/hello-world'
    | '/learn/git/hello-world'
    | '/learn/python/whiteboarding-essentials'
    | '/blog/frontend-design'
    | '/blog/react'
    | '/blog/soft-skills'
    | '/learn/ai'
    | '/learn/dsa'
    | '/learn/git'
    | '/learn/math'
    | '/learn/python'
    | '/learn/math/hello-world/advanced'
    | '/learn/math/hello-world/examples'
    | '/learn/math/hello-world'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/learn'
    | '/about'
    | '/game'
    | '/home'
    | '/blog/'
    | '/learn/'
    | '/learn/math/hello-world'
    | '/blog/frontend-design/microfrontends-part1'
    | '/blog/frontend-design/microfrontends-part2'
    | '/blog/frontend-design/microfrontends-part3'
    | '/blog/react/memo-monster'
    | '/blog/soft-skills/learn-names'
    | '/learn/ai/hello-world'
    | '/learn/dsa/hello-world'
    | '/learn/git/hello-world'
    | '/learn/python/whiteboarding-essentials'
    | '/blog/frontend-design/'
    | '/blog/react/'
    | '/blog/soft-skills/'
    | '/learn/ai/'
    | '/learn/dsa/'
    | '/learn/git/'
    | '/learn/math/'
    | '/learn/python/'
    | '/learn/math/hello-world/advanced'
    | '/learn/math/hello-world/examples'
    | '/learn/math/hello-world/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRouteRoute: typeof BlogRouteRouteWithChildren
  LearnRouteRoute: typeof LearnRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  GameRoute: typeof GameRoute
  HomeRoute: typeof HomeRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRouteRoute: BlogRouteRouteWithChildren,
  LearnRouteRoute: LearnRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  GameRoute: GameRoute,
  HomeRoute: HomeRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/blog",
        "/learn",
        "/about",
        "/game",
        "/home"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/blog": {
      "filePath": "blog/route.tsx",
      "children": [
        "/blog/",
        "/blog/frontend-design/microfrontends-part1",
        "/blog/frontend-design/microfrontends-part2",
        "/blog/frontend-design/microfrontends-part3",
        "/blog/react/memo-monster",
        "/blog/soft-skills/learn-names",
        "/blog/frontend-design/",
        "/blog/react/",
        "/blog/soft-skills/"
      ]
    },
    "/learn": {
      "filePath": "learn/route.tsx",
      "children": [
        "/learn/",
        "/learn/math/hello-world",
        "/learn/ai/hello-world",
        "/learn/dsa/hello-world",
        "/learn/git/hello-world",
        "/learn/python/whiteboarding-essentials",
        "/learn/ai/",
        "/learn/dsa/",
        "/learn/git/",
        "/learn/math/",
        "/learn/python/"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/game": {
      "filePath": "game.tsx"
    },
    "/home": {
      "filePath": "home.tsx"
    },
    "/blog/": {
      "filePath": "blog/index.tsx",
      "parent": "/blog"
    },
    "/learn/": {
      "filePath": "learn/index.tsx",
      "parent": "/learn"
    },
    "/learn/math/hello-world": {
      "filePath": "learn/math/hello-world/route.tsx",
      "parent": "/learn",
      "children": [
        "/learn/math/hello-world/advanced",
        "/learn/math/hello-world/examples",
        "/learn/math/hello-world/"
      ]
    },
    "/blog/frontend-design/microfrontends-part1": {
      "filePath": "blog/frontend-design/microfrontends-part1.tsx",
      "parent": "/blog"
    },
    "/blog/frontend-design/microfrontends-part2": {
      "filePath": "blog/frontend-design/microfrontends-part2.tsx",
      "parent": "/blog"
    },
    "/blog/frontend-design/microfrontends-part3": {
      "filePath": "blog/frontend-design/microfrontends-part3.tsx",
      "parent": "/blog"
    },
    "/blog/react/memo-monster": {
      "filePath": "blog/react/memo-monster.tsx",
      "parent": "/blog"
    },
    "/blog/soft-skills/learn-names": {
      "filePath": "blog/soft-skills/learn-names.jsx",
      "parent": "/blog"
    },
    "/learn/ai/hello-world": {
      "filePath": "learn/ai/hello-world.tsx",
      "parent": "/learn"
    },
    "/learn/dsa/hello-world": {
      "filePath": "learn/dsa/hello-world.tsx",
      "parent": "/learn"
    },
    "/learn/git/hello-world": {
      "filePath": "learn/git/hello-world.tsx",
      "parent": "/learn"
    },
    "/learn/python/whiteboarding-essentials": {
      "filePath": "learn/python/whiteboarding-essentials.tsx",
      "parent": "/learn"
    },
    "/blog/frontend-design/": {
      "filePath": "blog/frontend-design/index.tsx",
      "parent": "/blog"
    },
    "/blog/react/": {
      "filePath": "blog/react/index.tsx",
      "parent": "/blog"
    },
    "/blog/soft-skills/": {
      "filePath": "blog/soft-skills/index.tsx",
      "parent": "/blog"
    },
    "/learn/ai/": {
      "filePath": "learn/ai/index.tsx",
      "parent": "/learn"
    },
    "/learn/dsa/": {
      "filePath": "learn/dsa/index.tsx",
      "parent": "/learn"
    },
    "/learn/git/": {
      "filePath": "learn/git/index.tsx",
      "parent": "/learn"
    },
    "/learn/math/": {
      "filePath": "learn/math/index.tsx",
      "parent": "/learn"
    },
    "/learn/python/": {
      "filePath": "learn/python/index.tsx",
      "parent": "/learn"
    },
    "/learn/math/hello-world/advanced": {
      "filePath": "learn/math/hello-world/advanced.lazy.tsx",
      "parent": "/learn/math/hello-world"
    },
    "/learn/math/hello-world/examples": {
      "filePath": "learn/math/hello-world/examples.lazy.tsx",
      "parent": "/learn/math/hello-world"
    },
    "/learn/math/hello-world/": {
      "filePath": "learn/math/hello-world/index.tsx",
      "parent": "/learn/math/hello-world"
    }
  }
}
ROUTE_MANIFEST_END */
