/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as HomeImport } from './routes/home'
import { Route as GameImport } from './routes/game'
import { Route as AboutImport } from './routes/about'
import { Route as BlogRouteImport } from './routes/blog/route'
import { Route as IndexImport } from './routes/index'
import { Route as BlogIndexImport } from './routes/blog/index'
import { Route as BlogPostsSoftSkillsIndexImport } from './routes/blog/posts/soft-skills/index'
import { Route as BlogPostsFrontendDesignIndexImport } from './routes/blog/posts/frontend-design/index'
import { Route as BlogPostsSoftSkillsLearnNamesImport } from './routes/blog/posts/soft-skills/learn-names'
import { Route as BlogPostsFrontendDesignMicrofrontendsPart3Import } from './routes/blog/posts/frontend-design/microfrontends-part3'
import { Route as BlogPostsFrontendDesignMicrofrontendsPart2Import } from './routes/blog/posts/frontend-design/microfrontends-part2'
import { Route as BlogPostsFrontendDesignMicrofrontendsPart1Import } from './routes/blog/posts/frontend-design/microfrontends-part1'

// Create/Update Routes

const HomeRoute = HomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRoute,
} as any)

const GameRoute = GameImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const BlogRouteRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const BlogIndexRoute = BlogIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRouteRoute,
} as any)

const BlogPostsSoftSkillsIndexRoute = BlogPostsSoftSkillsIndexImport.update({
  id: '/posts/soft-skills/',
  path: '/posts/soft-skills/',
  getParentRoute: () => BlogRouteRoute,
} as any)

const BlogPostsFrontendDesignIndexRoute =
  BlogPostsFrontendDesignIndexImport.update({
    id: '/posts/frontend-design/',
    path: '/posts/frontend-design/',
    getParentRoute: () => BlogRouteRoute,
  } as any)

const BlogPostsSoftSkillsLearnNamesRoute =
  BlogPostsSoftSkillsLearnNamesImport.update({
    id: '/posts/soft-skills/learn-names',
    path: '/posts/soft-skills/learn-names',
    getParentRoute: () => BlogRouteRoute,
  } as any)

const BlogPostsFrontendDesignMicrofrontendsPart3Route =
  BlogPostsFrontendDesignMicrofrontendsPart3Import.update({
    id: '/posts/frontend-design/microfrontends-part3',
    path: '/posts/frontend-design/microfrontends-part3',
    getParentRoute: () => BlogRouteRoute,
  } as any)

const BlogPostsFrontendDesignMicrofrontendsPart2Route =
  BlogPostsFrontendDesignMicrofrontendsPart2Import.update({
    id: '/posts/frontend-design/microfrontends-part2',
    path: '/posts/frontend-design/microfrontends-part2',
    getParentRoute: () => BlogRouteRoute,
  } as any)

const BlogPostsFrontendDesignMicrofrontendsPart1Route =
  BlogPostsFrontendDesignMicrofrontendsPart1Import.update({
    id: '/posts/frontend-design/microfrontends-part1',
    path: '/posts/frontend-design/microfrontends-part1',
    getParentRoute: () => BlogRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameImport
      parentRoute: typeof rootRoute
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeImport
      parentRoute: typeof rootRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexImport
      parentRoute: typeof BlogRouteImport
    }
    '/blog/posts/frontend-design/microfrontends-part1': {
      id: '/blog/posts/frontend-design/microfrontends-part1'
      path: '/posts/frontend-design/microfrontends-part1'
      fullPath: '/blog/posts/frontend-design/microfrontends-part1'
      preLoaderRoute: typeof BlogPostsFrontendDesignMicrofrontendsPart1Import
      parentRoute: typeof BlogRouteImport
    }
    '/blog/posts/frontend-design/microfrontends-part2': {
      id: '/blog/posts/frontend-design/microfrontends-part2'
      path: '/posts/frontend-design/microfrontends-part2'
      fullPath: '/blog/posts/frontend-design/microfrontends-part2'
      preLoaderRoute: typeof BlogPostsFrontendDesignMicrofrontendsPart2Import
      parentRoute: typeof BlogRouteImport
    }
    '/blog/posts/frontend-design/microfrontends-part3': {
      id: '/blog/posts/frontend-design/microfrontends-part3'
      path: '/posts/frontend-design/microfrontends-part3'
      fullPath: '/blog/posts/frontend-design/microfrontends-part3'
      preLoaderRoute: typeof BlogPostsFrontendDesignMicrofrontendsPart3Import
      parentRoute: typeof BlogRouteImport
    }
    '/blog/posts/soft-skills/learn-names': {
      id: '/blog/posts/soft-skills/learn-names'
      path: '/posts/soft-skills/learn-names'
      fullPath: '/blog/posts/soft-skills/learn-names'
      preLoaderRoute: typeof BlogPostsSoftSkillsLearnNamesImport
      parentRoute: typeof BlogRouteImport
    }
    '/blog/posts/frontend-design/': {
      id: '/blog/posts/frontend-design/'
      path: '/posts/frontend-design'
      fullPath: '/blog/posts/frontend-design'
      preLoaderRoute: typeof BlogPostsFrontendDesignIndexImport
      parentRoute: typeof BlogRouteImport
    }
    '/blog/posts/soft-skills/': {
      id: '/blog/posts/soft-skills/'
      path: '/posts/soft-skills'
      fullPath: '/blog/posts/soft-skills'
      preLoaderRoute: typeof BlogPostsSoftSkillsIndexImport
      parentRoute: typeof BlogRouteImport
    }
  }
}

// Create and export the route tree

interface BlogRouteRouteChildren {
  BlogIndexRoute: typeof BlogIndexRoute
  BlogPostsFrontendDesignMicrofrontendsPart1Route: typeof BlogPostsFrontendDesignMicrofrontendsPart1Route
  BlogPostsFrontendDesignMicrofrontendsPart2Route: typeof BlogPostsFrontendDesignMicrofrontendsPart2Route
  BlogPostsFrontendDesignMicrofrontendsPart3Route: typeof BlogPostsFrontendDesignMicrofrontendsPart3Route
  BlogPostsSoftSkillsLearnNamesRoute: typeof BlogPostsSoftSkillsLearnNamesRoute
  BlogPostsFrontendDesignIndexRoute: typeof BlogPostsFrontendDesignIndexRoute
  BlogPostsSoftSkillsIndexRoute: typeof BlogPostsSoftSkillsIndexRoute
}

const BlogRouteRouteChildren: BlogRouteRouteChildren = {
  BlogIndexRoute: BlogIndexRoute,
  BlogPostsFrontendDesignMicrofrontendsPart1Route:
    BlogPostsFrontendDesignMicrofrontendsPart1Route,
  BlogPostsFrontendDesignMicrofrontendsPart2Route:
    BlogPostsFrontendDesignMicrofrontendsPart2Route,
  BlogPostsFrontendDesignMicrofrontendsPart3Route:
    BlogPostsFrontendDesignMicrofrontendsPart3Route,
  BlogPostsSoftSkillsLearnNamesRoute: BlogPostsSoftSkillsLearnNamesRoute,
  BlogPostsFrontendDesignIndexRoute: BlogPostsFrontendDesignIndexRoute,
  BlogPostsSoftSkillsIndexRoute: BlogPostsSoftSkillsIndexRoute,
}

const BlogRouteRouteWithChildren = BlogRouteRoute._addFileChildren(
  BlogRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/game': typeof GameRoute
  '/home': typeof HomeRoute
  '/blog/': typeof BlogIndexRoute
  '/blog/posts/frontend-design/microfrontends-part1': typeof BlogPostsFrontendDesignMicrofrontendsPart1Route
  '/blog/posts/frontend-design/microfrontends-part2': typeof BlogPostsFrontendDesignMicrofrontendsPart2Route
  '/blog/posts/frontend-design/microfrontends-part3': typeof BlogPostsFrontendDesignMicrofrontendsPart3Route
  '/blog/posts/soft-skills/learn-names': typeof BlogPostsSoftSkillsLearnNamesRoute
  '/blog/posts/frontend-design': typeof BlogPostsFrontendDesignIndexRoute
  '/blog/posts/soft-skills': typeof BlogPostsSoftSkillsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/game': typeof GameRoute
  '/home': typeof HomeRoute
  '/blog': typeof BlogIndexRoute
  '/blog/posts/frontend-design/microfrontends-part1': typeof BlogPostsFrontendDesignMicrofrontendsPart1Route
  '/blog/posts/frontend-design/microfrontends-part2': typeof BlogPostsFrontendDesignMicrofrontendsPart2Route
  '/blog/posts/frontend-design/microfrontends-part3': typeof BlogPostsFrontendDesignMicrofrontendsPart3Route
  '/blog/posts/soft-skills/learn-names': typeof BlogPostsSoftSkillsLearnNamesRoute
  '/blog/posts/frontend-design': typeof BlogPostsFrontendDesignIndexRoute
  '/blog/posts/soft-skills': typeof BlogPostsSoftSkillsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/game': typeof GameRoute
  '/home': typeof HomeRoute
  '/blog/': typeof BlogIndexRoute
  '/blog/posts/frontend-design/microfrontends-part1': typeof BlogPostsFrontendDesignMicrofrontendsPart1Route
  '/blog/posts/frontend-design/microfrontends-part2': typeof BlogPostsFrontendDesignMicrofrontendsPart2Route
  '/blog/posts/frontend-design/microfrontends-part3': typeof BlogPostsFrontendDesignMicrofrontendsPart3Route
  '/blog/posts/soft-skills/learn-names': typeof BlogPostsSoftSkillsLearnNamesRoute
  '/blog/posts/frontend-design/': typeof BlogPostsFrontendDesignIndexRoute
  '/blog/posts/soft-skills/': typeof BlogPostsSoftSkillsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/about'
    | '/game'
    | '/home'
    | '/blog/'
    | '/blog/posts/frontend-design/microfrontends-part1'
    | '/blog/posts/frontend-design/microfrontends-part2'
    | '/blog/posts/frontend-design/microfrontends-part3'
    | '/blog/posts/soft-skills/learn-names'
    | '/blog/posts/frontend-design'
    | '/blog/posts/soft-skills'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/game'
    | '/home'
    | '/blog'
    | '/blog/posts/frontend-design/microfrontends-part1'
    | '/blog/posts/frontend-design/microfrontends-part2'
    | '/blog/posts/frontend-design/microfrontends-part3'
    | '/blog/posts/soft-skills/learn-names'
    | '/blog/posts/frontend-design'
    | '/blog/posts/soft-skills'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/about'
    | '/game'
    | '/home'
    | '/blog/'
    | '/blog/posts/frontend-design/microfrontends-part1'
    | '/blog/posts/frontend-design/microfrontends-part2'
    | '/blog/posts/frontend-design/microfrontends-part3'
    | '/blog/posts/soft-skills/learn-names'
    | '/blog/posts/frontend-design/'
    | '/blog/posts/soft-skills/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRouteRoute: typeof BlogRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  GameRoute: typeof GameRoute
  HomeRoute: typeof HomeRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRouteRoute: BlogRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  GameRoute: GameRoute,
  HomeRoute: HomeRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/blog",
        "/about",
        "/game",
        "/home"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/blog": {
      "filePath": "blog/route.tsx",
      "children": [
        "/blog/",
        "/blog/posts/frontend-design/microfrontends-part1",
        "/blog/posts/frontend-design/microfrontends-part2",
        "/blog/posts/frontend-design/microfrontends-part3",
        "/blog/posts/soft-skills/learn-names",
        "/blog/posts/frontend-design/",
        "/blog/posts/soft-skills/"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/game": {
      "filePath": "game.tsx"
    },
    "/home": {
      "filePath": "home.tsx"
    },
    "/blog/": {
      "filePath": "blog/index.tsx",
      "parent": "/blog"
    },
    "/blog/posts/frontend-design/microfrontends-part1": {
      "filePath": "blog/posts/frontend-design/microfrontends-part1.tsx",
      "parent": "/blog"
    },
    "/blog/posts/frontend-design/microfrontends-part2": {
      "filePath": "blog/posts/frontend-design/microfrontends-part2.tsx",
      "parent": "/blog"
    },
    "/blog/posts/frontend-design/microfrontends-part3": {
      "filePath": "blog/posts/frontend-design/microfrontends-part3.tsx",
      "parent": "/blog"
    },
    "/blog/posts/soft-skills/learn-names": {
      "filePath": "blog/posts/soft-skills/learn-names.jsx",
      "parent": "/blog"
    },
    "/blog/posts/frontend-design/": {
      "filePath": "blog/posts/frontend-design/index.tsx",
      "parent": "/blog"
    },
    "/blog/posts/soft-skills/": {
      "filePath": "blog/posts/soft-skills/index.tsx",
      "parent": "/blog"
    }
  }
}
ROUTE_MANIFEST_END */
